### ISSUE TITLE
Get position of window relative to others on desktop

### ISSUE THREAD

**Issue by chipsenkbeil** [koekeishiya/chunkwm#470] opened 2018-07-27 14:08 UTC
Is there a way to query for the position of a window relative to others on the desktop? My thought process is that if I could understand when the far right window is active on my left monitor and capture when I want to perform the action to move east, I could intercept to change the focus to the next monitor and select its west-most window. This would let me seamlessly move between monitors.

I'd still need to figure out my monitor position in a 2 or 3 monitor setup (which is left-most, which is center, etc), but the window position seems to be the bigger challenge.

**Comment by koekeishiya** [comment] 2018-08-03 10:45
This is not possible to do with the query system as of now, and probably won't be implemented.

What you are trying to achieve seems like a duplicate of #456

**Closed by koekeishiya** 2018-08-03 10:45 UTC
