### ISSUE TITLE
Hidden windows will keep occupying a leaf

### ISSUE THREAD

**Issue by blahsd** [koekeishiya/chunkwm#350] opened 2018-02-26 11:38 UTC
Often hiding a window instead of quitting the application will not free the leaf, with the result that the part of the screen that was dedicated to that app will remain empty. 

It appears that it's always the same apps that cause this behaviour, leading me to think that it's possibly an issue with different apps handling the "hide" behaviour differently. Apps that consistently (albeit not 100%) create this issue for me are: 

- Preview
- Spotify 

Besides preview, all stock apps seem unaffected. 

This behaviour will not happen if the hidden app was previously the only app in the workspace, eg, if I only have preview open, then hide it, then open a new app, this app will take up the entire workspace correctly.

**Comment by CestDiego** [comment] 2018-03-01 21:52
This happens with Slack as well

**Comment by koekeishiya** [comment] 2018-03-02 09:19
No idea how this can even be a problem. All applications are handled the same way, through *NSWorkspace notifications (https://github.com/koekeishiya/chunkwm/blob/master/src/core/dispatch/workspace.mm#L89)
(https://github.com/koekeishiya/chunkwm/blob/master/src/core/dispatch/workspace.mm#L133)

Can you enable logging (debug mode)?
Add this to your config file:
`chunkc core::log_level debug`
`chunkc core::log_file  ~/chunkwm_tmp_log.txt`

you can then view the log file from a terminal using *tail*:
`tail -f ~/chunkwm_tmp_log.txt`

You're basically looking to see if this line is outputted: https://github.com/koekeishiya/chunkwm/blob/master/src/core/callback.cpp#L266

**Comment by blahsd** [comment] 2018-03-03 10:54
I might be doing something wrong but it appears that both running these
commands and having them in .chunkwmrc does not have any effect on
chunkwm_tmp_log.txt. Is it supposed to only print out at certain times?


On 2 March 2018 at 10:19:47, Åsmund Vikane (notifications@github.com) wrote:

No idea how this can even be a problem. All applications are handled the
same way, through *NSWorkspace notifications (
https://github.com/koekeishiya/chunkwm/blob/master/src/core/dispatch/workspace.mm#L89
)
(
https://github.com/koekeishiya/chunkwm/blob/master/src/core/dispatch/workspace.mm#L133
)

Can you enable logging (debug mode)?
Add this to your config file:
chunkc core::log_level debug
chunkc core::log_file ~/chunkwm_tmp_log.txt

you can then view the log file from a terminal using *tail*:
tail -f ~/chunkwm_tmp_log.txt

You're basically looking to see if this line is outputted:
https://github.com/koekeishiya/chunkwm/blob/master/src/core/callback.cpp#L266

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/koekeishiya/chunkwm/issues/350#issuecomment-369866164>,
or mute the thread

**Comment by koekeishiya** [comment] 2018-03-04 10:49
You need to set the options in the config file and then do a restart of chunkwm.

**Comment by koekeishiya** [comment] 2019-04-15 19:40
Unable to reproduce this with spotify and preview. closing.

**Closed by koekeishiya** 2019-04-15 19:40 UTC
Labels: bug, need steps to reproduce
