### ISSUE TITLE
All monitors identified as 1 when in native-fullscreen

### ISSUE THREAD

**Issue by stephenprater** [koekeishiya/chunkwm#462] opened 2018-07-07 21:36 UTC
When running an app in native fullscreen (in this case Alacritty, but it works with others as well)  - issuing `chunkc tiling:query --monitor id` will always return 1.

I'm _pretty sure_ this is because the "native-fullscreen" thing makes a virtual space for the app so that it can be switched to with system-level `ctrl-<arrow>`.

This affects `chunkc` monitor switching as trying to switch the monitor _to_ 1 when it thinks it's already _on 1_ will not work.

Apologies if this has already been discussed - I see that support for full-screen applications was added in May, but it's not clear to me from reading the associated issues if this is fixable or not.

**Comment by koekeishiya** [comment] 2018-07-07 22:18
Fairly sure this is not fixable. Whenever I have a fullscreen window active on a secondary monitor, macOS incorrectly reports the active desktop as the first mission-control desktop of the primary monitor.

**Comment by koekeishiya** [comment] 2018-07-08 09:39
See my previous reply: I believe this is actually a bug in macOS Mojave.
Unless you are happening to be running on High Sierra, in which case this is likely a regression in *chunkwm*. Can you post which OS you are experiencing this on?

I do experience this issue (currently on latest Mojave Beta), but I do not recall having this issue when I was using High Sierra. The reason for this is that this exact issue has caused #127 to behave differently than what it was when I implemented that change..

**Comment by stephenprater** [comment] 2018-07-08 17:07
I'm running on Sierra.   Too bad about it not being fixable, but understood.

**Comment by koekeishiya** [comment] 2018-08-09 07:50
This may have been fixed on master. We moved to a different way of detecting the active space in commit 65a7bcf57d470b373c2702e6bb71b8bcf6f272f4

Will confirm later today if that commit also fixed this issue.

**Comment by koekeishiya** [comment] 2018-08-09 14:44
Confirmed that this has been fixed on master.

**Closed by koekeishiya** 2018-08-09 14:44 UTC
