### ISSUE TITLE
chunkwm crashes when clicking on desktop in monocle mode

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/chunkwm#486] opened 2018-08-11 00:13 UTC
This is running the latest `master`

STR:

1. Ensure focus follow mouse is on
1. Ensure focus borders are on
1. Place a desktop in monocle mode
1. Click on the desktop background to unfocus the currently focused window
1. use mouse to focus the front most monocle window

Expected Result:
No crash

Actual Result
```
Aug 10 17:09:56 Constance com.apple.xpc.launchd[1] (homebrew.mxcl.chunkwm[10142]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Aug 10 17:09:56 Constance chunkwm[10258]: objc[10258]: Class OverlayView is implemented in both /usr/local/opt/chunkwm/share/chunkwm/plugins/border.so (0x1079e5910) and /usr/local/opt/chunkwm/share/chunkwm/plugins/tiling.so (0x107a09540). One of the two will be used. Which one is undefined.
```

**Comment by koekeishiya** [comment] 2018-08-11 08:12
I'm unable to reproduce this. Do you have some scripts utilizing any kind of query commands or something, that is running?

**Comment by koekeishiya** [comment] 2018-08-12 08:55
fixed on master.

**Closed by koekeishiya** 2018-08-12 08:55 UTC

**Comment by chrishoage** [comment] 2018-08-12 18:41
Confirmed fix, thanks for the incredibly quick fix 😄
