### ISSUE TITLE
Popup window opens behind floating window

### ISSUE THREAD

**Issue by dsanson** [koekeishiya/chunkwm#229] opened 2017-09-19 18:18 UTC
When I have `window_float_topmost` set to `1` in `.chunkwmrc`, and I put a window into "floating" mode, popup windows, like the print dialog in Preview, are displayed behind the window, making them hard to use! So for the moment, I've set `window_float_topmost` back to `0`.

<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/14331/30607965-74d44a7c-9d3c-11e7-9d6d-a911f9508077.png">

**Comment by crisidev** [comment] 2017-09-19 19:24
The same happens to me.

**Comment by koekeishiya** [comment] 2017-09-19 20:28
Not sure what can be done about this. I believe the issue exists because the modal popup panels are unable to have the *floating window level* set, causing them to fall behind the *main* window.

**Comment by dsanson** [comment] 2017-09-19 22:47
That makes sense. I don't know enough about the APIs to know what is possible. I don't suppose there is a window level below the modal popup panel level but above the normal window level, which would allow for a less aggressive version of `window_float_topmost`?

**Comment by koekeishiya** [comment] 2017-09-20 10:14
These are the window  levels that I know about:
```
enum _CGCommonWindowLevelKey
        {
            kCGBaseWindowLevelKey               =  0,
            kCGMinimumWindowLevelKey            =  1,
            kCGDesktopWindowLevelKey            =  2,
            kCGBackstopMenuLevelKey             =  3,
            kCGNormalWindowLevelKey             =  4,
            kCGFloatingWindowLevelKey           =  5,
            kCGTornOffMenuWindowLevelKey        =  6,
            kCGDockWindowLevelKey               =  7,
            kCGMainMenuWindowLevelKey           =  8,
            kCGStatusWindowLevelKey             =  9,
            kCGModalPanelWindowLevelKey         = 10,
            kCGPopUpMenuWindowLevelKey          = 11,
            kCGDraggingWindowLevelKey           = 12,
            kCGScreenSaverWindowLevelKey        = 13,
            kCGMaximumWindowLevelKey            = 14,
            kCGOverlayWindowLevelKey            = 15,
            kCGHelpWindowLevelKey               = 16,
            kCGUtilityWindowLevelKey            = 17,
            kCGDesktopIconWindowLevelKey        = 18,
            kCGCursorWindowLevelKey             = 19,
            kCGAssistiveTechHighWindowLevelKey  = 20,
            kCGNumberOfWindowLevelKeys
        }; typedef int32_t CGWindowLevelKey;
```

kCGNormalWindowLevelKey is the level most windows use by default.
kCGFloatingWindowLevelKey is what chunkwm currently uses to make them topmost.

**Comment by koekeishiya** [comment] 2017-09-29 14:39
I've experimented with a few other window levels, but all the relevant ones seem to cause the same behaviour as described in the issue.

**Comment by koekeishiya** [comment] 2018-06-04 20:02
Note to self:

After experimenting some more, this turns out to be a problem because we do not actually get notified about the modal window being created or getting focus at all.

**Comment by koekeishiya** [comment] 2018-06-04 20:52
Would you look at that. Resolved on master. I can finally start using this option now!

**Comment by dominiklohmann** [comment] 2018-06-14 08:56
Just noticed a bug in your implementation here, if a modal opens another modal that second one should be frontmost.

This happens in the Xcode new file dialog for example:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4488655/41401958-6466ff9c-6fc1-11e8-8ee7-459db723fed9.png">

**Comment by koekeishiya** [comment] 2018-06-14 11:34
Note to self: We need to track all modal windows and have them ALSO subscribe to notifications.

**Comment by dominiklohmann** [comment] 2018-06-14 16:55
It works, although there is a bit of lag sometimes (seems to be quite random, I cannot always reproduce it). If the lag happens it looks like this: https://gfycat.com/FantasticBlandAmericanwigeon

Other than that I'd consider this fixed.

**Comment by koekeishiya** [comment] 2018-06-14 17:14
Try the latest master; got rid of some unnecessary cruft due to code reuse.
Hopefully it should make it a little bit snappier, although I sort of doubt it.

**Comment by dominiklohmann** [comment] 2018-06-14 17:21
> I sort of doubt it.

No need to, feels much faster now. Opened and closed the modal like 50 times and haven't gotten the lag once (before that I'd get it like 20% of the time).

**Comment by koekeishiya** [comment] 2018-06-14 17:23
Great! Closing this then.

Thanks again for all the testing, it really does help a lot :)

**Closed by koekeishiya** 2018-06-14 17:23 UTC
Labels: bug

**Comment by dominiklohmann** [comment] 2018-06-19 15:26
Found another one: Color picker in iTerm2. I believe this is called a popover view.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/4488655/41607224-cfafac9a-73e5-11e8-922f-dd4a6e2c8c48.png">

**Comment by koekeishiya** [comment] 2018-06-19 15:46
Can you run it through the accessibility inspector and see if it posts any notification?

**Comment by dominiklohmann** [comment] 2018-06-19 15:52
Just the usual AXValueChanged spam from iTerm2. Not really sure how to debug this at all.

**Comment by dominiklohmann** [comment] 2018-06-19 15:56
AXPopover role is the best I've got.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/4488655/41608963-032e41f4-73ea-11e8-9fb6-5a4da32bc505.png">
