### ISSUE TITLE
Cannot focus desktops. Log says <unknown> process terminated

### ISSUE THREAD

**Issue by wpix** [koekeishiya/chunkwm#626] opened 2019-05-21 10:04 UTC
I cannot seem to make desktop-related functions work. Whenever I focused on a desktop, nothing changed but all my windows/desktops got re-registrated.
For example, when I input `chunkc tiling::desktop --focus prev` 
The debugging log reports:
```
DEBUG:     command: 'f', arg: 'prev'
DEBUG: chunkwm: processing event of type 'ChunkWM_PluginLoad'
```
And then all my windows got re-registrated and changed the original layouts. 

<details>
<summary>Full log details here</summary>
<br>
2019-05-21 05:45:39 DEBUG: command: 'f', arg: 'next'<br />
2019-05-21 05:45:39 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginLoad'<br />
2019-05-21 05:45:39 DEBUG: Plugin Details<br />
API Version 8<br />
FileName 'plugin.mm'<br />
PluginName 'Border'<br />
PluginVersion '0.3.5'<br />
2019-05-21 05:45:39 DEBUG: chunkwm: plugin 'border.so' loaded!<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_application_launched'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_application_unhidden'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_application_activated'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_application_deactivated'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_created'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_focused'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_destroyed'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_moved'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_resized'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_minimized'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_window_deminimized'<br />
2019-05-21 05:45:39 DEBUG: Plugin 'Border' subscribed to 'chunkwm_export_space_changed'<br />
2019-05-21 05:45:39 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginLoad'<br />
2019-05-21 05:45:39 DEBUG: Plugin Details<br />
API Version 8<br />
FileName 'plugin.mm'<br />
PluginName 'Tiling'<br />
PluginVersion '0.3.16'<br />
2019-05-21 05:45:40 DEBUG: carbon: process details<br />
Name: <unknown><br />
PID: 0<br />
PSN: 1253682 0<br />
Policy: 0<br />
Background: 0<br />
2019-05-21 05:45:40 DEBUG: 0:<unknown> process terminated; cancel registration of window notifications!!!<br />
2019-05-21 05:45:40 DEBUG: chunkwm: plugin 'tiling.so' loaded!<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_application_launched'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_application_terminated'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_application_hidden'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_application_unhidden'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_application_activated'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_created'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_destroyed'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_minimized'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_deminimized'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_focused'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_moved'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_resized'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_title_changed'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_window_sheet_created'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_space_changed'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_display_changed'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_display_resized'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Tiling' subscribed to 'chunkwm_export_display_moved'<br />
2019-05-21 05:45:40 DEBUG: 2:desktop 3334:0:iTerm2:1. Ying: tail -f /tmp/chunkwm.log (tail)<br />
2019-05-21 05:45:40 DEBUG: chunkwm:Tiling:focused_window_float<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginLoad'<br />
2019-05-21 05:45:40 DEBUG: Plugin Details<br />
API Version 8<br />
FileName 'plugin.cpp'<br />
PluginName 'Focus Follows Mouse'<br />
PluginVersion '0.4.0'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: plugin 'ffm.so' loaded!<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Focus Follows Mouse' subscribed to 'chunkwm_export_application_activated'<br />
2019-05-21 05:45:40 DEBUG: Plugin 'Focus Follows Mouse' subscribed to 'chunkwm_export_window_focused'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'<br />
2019-05-21 05:45:40 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginCommand'
</details>
  
  

Specifically, there is a line says:
```
DEBUG: 0:<unknown> process terminated; cancel registration of window notifications!!!
```

Sometimes there is also
```
DEBUG: chunkwm: processing event of type 'ChunkWM_SpaceChanged'
DEBUG: Finder:<unknown> is not destructible, ignore!
```

I searched many previous issues, for example, uncheck the `Automatically rearrange Space based on most recent use`, mark the config fire `chunkc set window_region_locked` as 0. Did not seem to work. 

  
 

I've been stuck for two days here 😂 any help will be very much appreciated.

**Comment by wpix** [comment] 2019-05-21 10:27
Here is my config file [dotfiles/.chunkwmrc at master · wpix/dotfiles](https://github.com/wpix/dotfiles/blob/master/chunkwm/.chunkwmrc)  
  
Also a comment I made in one previous issue that might be related. 
https://github.com/koekeishiya/chunkwm/issues/620#issuecomment-493678566

**Comment by dominiklohmann** [comment] 2019-05-21 10:32
The usual plethora of questions:

- What version of macOS are you running?
- Are you running chunkwm from master? (`chunkwm --version` returns `chunkwm 0.4.9 (cb99)` for current master as of this reply)
- Are you using the scripting addition (chwm-sa)?
- Do you have the AX permissions enabled?

**Comment by wpix** [comment] 2019-05-21 10:39
> The usual plethora of questions:
> 
> * What version of macOS are you running?
> * Are you running chunkwm from master? (`chunkwm --version` returns `chunkwm 0.4.9 (cb99)` for current master as of this reply)
> * Are you using the scripting addition (chwm-sa)?
> * Do you have the AX permissions enabled?

Thanks for the info! 
+ macOS
System Version               :  macOS 10.14.4 (18E226)
Kernel Version               :  Darwin 18.5.0
System Integrity Protection  :  Disabled

+ chunkwm version
`chunkwm 0.4.9 (cb99)`

+ chwm-sa
Yes I am running the scripting addition. Here is a link to details https://github.com/koekeishiya/chunkwm/issues/620#issuecomment-493679751

+ AX permissions
I did `chmod +x ~/.chunkwmrc` but not sure how to check if I have the right permission.

**Comment by dominiklohmann** [comment] 2019-05-21 10:44
> AX permissions

Sorry, should've written that one out. I'm referring to the accessibility API permissions you grant in the security prefs. `chunkwm` refuses to run without them, so you're likely fine. 

> Here is a link to details [#620 (comment)](https://github.com/koekeishiya/chunkwm/issues/620#issuecomment-493679751)

I'm not entirely sure, but shouldn't you be running `pkill Dock` last? The scripting addition loads when you restart Dock.app, not when you start `chunkwm`. Alternatively reboot if you're running through `launchctl` which is what `brew services` does, as this will ensure that `chunkwm` is running before Dock.app launches.

**Comment by wpix** [comment] 2019-05-21 10:59
> running pkill Dock last
I've un-install, install, and restarted the service. Putting `pkill Dock` in the end does not work.
>Alternatively reboot
Also rebooted, did not notice any difference. 

When I try to focus other windows, the border of the the current window will disappear for ~2 seconds, and then come back. I'd think this is somehow an issue with the chwm-sa? Also searched issues on chwm-sa pages but cannot locate a solution.

**Comment by koekeishiya** [comment] 2019-05-21 11:03
The logs you posted in the other issue indicates that chwm-sa is working properly. To confirm this you can run ‘lsof -i :5050’

Sent from my iPhone

On 21 May 2019, at 13:01, wpix <notifications@github.com<mailto:notifications@github.com>> wrote:


running pkill Dock last
I've un-install, install, and restarted the service. Putting pkill Dock in the end does not work.
Alternatively reboot
Also rebooted, did not notice any difference.

When I try to focus other windows, the border of the the current window will disappear for ~2 seconds, and then come back. I'd think this is somehow an issue with the chwm-sa? Also searched issues on chwm-sa pages but cannot locate a solution.

**Comment by wpix** [comment] 2019-05-21 11:09
> The logs you posted in the other issue indicates that chwm-sa is working properly. To confirm this you can run ‘lsof -i :5050’
> […](#)

I got 
```bash
COMMAND PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Dock    298 Ying   30u  IPv4 0xa65e183f28d10b11      0t0  TCP localhost:mmcc (LISTEN)
```
I was configuring chwm-sa yesterday and tried everything I could find. All other functions in chunkwm work perfectly except desktop ones. Also cannot use `fade`

**Comment by BRS7** [comment] 2019-05-23 23:09
I have the same issue. While I was trying to reinstall chunkwm to try to fix the focus issue I noticed this warning when I ran `chunkwm --load-sa`. `chunkwm[10104:30574] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.`

**Comment by bradens** [comment] 2019-05-27 19:23
I have the same problem! None of the focus, create, or annihlate sa additions work.

**Comment by wpix** [comment] 2019-06-03 18:02
> Works! I think the problem was that i might not have had a correctly up-to-date version of chunkwm at the time i installed the SA, so reinstalling it and trying again worked.

Thank you for your help! It works now. Though I did already have the most up-to-date chunkwm version. When I run `brew upgrade chunkwm` it's already the HEAD version.

I think what might make a difference is `sudo chunkwm --load-sa`
I noticed that I never `sudo` ran this command before. Just a thought.

Thanks again 😊

**Comment by bradens** [comment] 2019-06-03 23:21
@wpix ah maybe that could have been the issue as well. 

I'm not sure on the process specific to this repo, but usually the author of the issue (you) can close your own if the problem is resolved.

**Comment by bradens** [comment] 2019-06-03 23:26
I just opened #632 addressing this.

**Comment by koekeishiya** [comment] 2019-06-04 16:25
There is no need to run the *--load-sa* command as root.
If you are having issues with functionality provided by the scripting addition on a system that is supported and working for other people, you likely have an out of date version installed / loaded.

The steps posted by bradens just a comment or two above this should resolva that.
Again note that there is no need to run *--load-sa* as root.

Closing this as it appears to be resolved for everyone involved.

**Closed by koekeishiya** 2019-06-04 16:25 UTC
