### ISSUE TITLE
Programs randomly sent to another desktop

### ISSUE THREAD

**Issue by blakeandrewwood** [koekeishiya/chunkwm#413] opened 2018-05-17 16:26 UTC
Sometimes I will have slack open on my 4th mission control desktop and it will randomly get sent to the 2nd. This also happens with several other applications. I have no specific configuration set for these programs. Any idea what is causing this?

**Comment by koekeishiya** [comment] 2018-05-17 16:32
That makes no sense. Can you post a gist / pastebin of your .chunkwmrc

**Comment by blakeandrewwood** [comment] 2018-05-18 00:07
@koekeishiya Yeah sure.

https://pastebin.com/PhiXjGuy

**Comment by koekeishiya** [comment] 2018-05-19 11:30
Hmm this still makes no sense for me. There is nothing that should cause windows to be sent to other desktops unless you specifically do so using a chunkc command, or define rules to do so.

**Comment by blakeandrewwood** [comment] 2018-05-21 20:46
My keybindings are minimal too, so I don't think I'm accidentally sending it. It seems to only happen when slack is open. It wants to be on desktop 2.

**Comment by blakeandrewwood** [comment] 2018-05-22 16:49
Never touched that, it's set to None already. It also only happens when I start switch around my various desktops. I use Opt+{1,2,3,4,5} as a shortcut to switch.

**Comment by njunxuan** [comment] 2018-05-24 10:54
I am experiencing this issue also. Is there anything we could do to help debug?

**Comment by ice8lue** [comment] 2018-05-28 15:16
Have the same problem too (three monitors with multiple desktops). Here are some steps that work every time for me:
* have a single program (screen filling)
* open  another window there (for example opening a single file window from IntelliJ, commit window,...)
* new window will open on that desktop, old one is resizes first and moved to next monitor then (and properly resized too, if needed)
* after closing the new window, old one stays on next monitor

**Comment by koekeishiya** [comment] 2018-05-28 15:22
Right, so the issue is between monitors, and not desktops.

Can any one of you try to build from source, where you comment both this line and the following one (L1307, and L1308):
https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/plugin.mm#L1307

**Comment by ice8lue** [comment] 2018-05-29 06:56
Tried and seems to work, didn't have the jumping again.

**Comment by blakeandrewwood** [comment] 2018-05-29 20:55
I have a dual monitor setup. 

Here's how it normally triggers for me:

Chrome on desktop 1 fill screen
IDE on desktop 2 fill screen
ITerm2 on desktop 3 fill screen
Empty desktop 4
Empty desktop 5
Nothing on my laptop screen (Secondary screen) for any desktop.

This is usually how I start out. I then begin to switch around the various desktops. I will then notice that Slack ends up on desktop 2, still filling the screen. IDE ends up on desktop 3, iterm2 on desktop 4.

**Comment by chipsenkbeil** [comment] 2018-05-30 20:17
@koekeishiya, I've had it happen when switching between spaces using the keyboard. Not sure how to reproduce, but it happens quite often. I'll try to pay attention to the next couple of occurrences to see if there's anything of note to report.

**Comment by jessemillar** [comment] 2018-06-19 20:27
It seems to happen for me when I use the mouse to drag a window from one monitor to another. e.g. I have two IntelliJ windows open, drag one from my rightmost monitor to my MacBook screen, the window now housed on my MacBook screen scales properly, I click on the rightmost monitor window with the mouse and the MacBook window either disappears or moves back to the rightmost monitor. When I use keyboard shortcuts to move the window between monitors, it doesn't seem to have an issue.

**Comment by medoix** [comment] 2018-06-27 00:27
Happens for me to for Slack specifically, i have noticed that if i have 
Workspace2 = Slack
Workspace3 = Firefox
Workspace4 = Firefox
Workspace5 = Kitty

If i mod+number switch workspace everything is fine
if i switch workspace using CMD+TAB to Slack when Slack is only the next workspace back or forward everything is fine
If i switch workspace using CMD+TAB to Slack app TWO workspaces back or forward from the Slack then Slack itself gets moved to the workspace before the Workspace App i am CMD+TAB'ing to.

I will try and take a screen capture

**Comment by zylent** [comment] 2018-08-21 01:10
So I've noticed this occurring as well, and can somewhat reproduce it.
If I use the kitty single instance launch option, new kitty windows always open on the workspace the parent instance originally launched on. 

I've switched to using open (old way of launching kitty), and configuring kitty to die when closed.

**Comment by bradens** [comment] 2018-08-21 16:59
FWIW i get this error as well, and i'm on a single monitor setup.  It seems that cmd-tab might have something to do with it. 

I can reproduce by opening a finder window, in space 3. 

Use move command to move the window to space 4.

Go to space 1.  Now cmd-tab to the finder app. 

The finder window is now in space 3. 

.chunkwmrc : https://github.com/bradens/dotfiles/blob/master/.chunkwmrc
version 0.4.5

**Comment by osipxd** [comment] 2018-10-04 11:40
In my case this problem was because of Mission Control configurations.
This checkbox should be unchecked.
![image](https://user-images.githubusercontent.com/3684355/46471669-47265c00-c7e3-11e8-8bad-6b52fbd437e2.png)

**Comment by bradens** [comment] 2018-10-04 13:40
Ahhh that fixed it for me.  Didn't even know that setting existed.  Thanks. 

Is it worth a mention somewhere in an FAQ or README?

**Comment by bradens** [comment] 2018-10-10 18:09
FWIW i think this issue can be closed now.

**Comment by chipsenkbeil** [comment] 2018-10-29 07:55
I think it has something to do with automatically jumping to other applications. For instance, I had a browser open on space 2 and a pdf open on space 5. When I clicked on a link in the pdf on space 5, I was sent to space 3 where my browser had moved to load the link.

Not sure what exactly is happening with this.

**Comment by chipsenkbeil** [comment] 2018-11-09 19:04
I'm going to assume that I also needed to turn the option off for switching to a space with open windows. I haven't noticed this happen since I did.

<img width="663" alt="screen shot 2018-11-09 at 1 03 01 pm" src="https://user-images.githubusercontent.com/2481802/48282641-dac0fd00-e41f-11e8-9c6b-629f5a3bd6b3.png">

**Comment by zylent** [comment] 2018-11-09 19:06
I don't have that box checked, and still see the issue. I think it's something to do with a parent process being assigned to a monitor, then all child processes spawn on that monitor vs the currently focused one.

**Closed** 2018-11-09 21:33 UTC
Labels: need steps to reproduce
