### ISSUE TITLE
Frequent segmentation faults after unlocking (maybe after waking up?) Cannot reproduce

### ISSUE THREAD

**Issue by enazn** [koekeishiya/chunkwm#339] opened 2018-02-08 19:28 UTC
I'm frequently having segmentation faults of chunkwm:

chunkwm: recv signal 11, printing stack trace
0   chunkwm                             0x000000010ff9efc8 _Z13SignalHandleri + 36
1   libsystem_platform.dylib            0x00007fff57402f5a _sigtramp + 26
2   libsystem_c.dylib                   0x00007fff57218927 __vfprintf + 16209
3   border.so                           0x00000001100eeece _Z10PluginMainPKcPv + 915
4   chunkwm                             0x000000010ff9e7e8 _ZL20DoNextWorkQueueEntryP10work_queue + 52
5   chunkwm                             0x000000010ff9c857 _Z17CompleteWorkQueueP10work_queue + 19
6   chunkwm                             0x000000010ff9acfd _Z31Callback_ChunkWM_DisplayChangedP11chunk_event + 315
7   chunkwm                             0x000000010ff9b869 _ZL17ProcessEventQueuePv + 153
8   libsystem_pthread.dylib             0x00007fff5740c6c1 _pthread_body + 340
9   libsystem_pthread.dylib             0x00007fff5740c56d _pthread_body + 0
10  libsystem_pthread.dylib             0x00007fff5740bc5d thread_start + 13

I really cannot correlate it with something I'm doing, but it never happens while I'm using the machine, it's always after I unlock it that my windows may suddenly reposition due to chunkwm crashing and starting again and setting the default view (i.e. before any rotations, resizings, etc that I usually do)

Would love to help debug the issue, but would need to have some help on what to try. I'm getting these 1 - 3 times a day usually, it doesn't happen every time I unlock.

Thanks!

**Comment by koekeishiya** [comment] 2018-02-08 19:48
This specific instance was caused by some operation that the border plugin tried to do upon a *display changed* event. The work that it tried to do is something leftover that is no longer necessary.

This has now been removed on master, and that should also fix the problem you have been seeing.

**Comment by enazn** [comment] 2018-02-08 20:03
Thanks for the super quick response!
I'll upgrade ASAP and report back if I see any issues.

**Comment by enazn** [comment] 2018-02-09 19:45
@koekeishiya I've compiled from head yesterday and I'm still getting crashes. It may be unrelated to my previous segfault, so let me know if you want me to create a new issue.

In fact, I think the issue is exactly the same, although now I didn't get any segfault in the logs. I collected the debug logs of everything that happened right after I unlocked my machine and when all my windows repositioned.

https://pastebin.com/SzGXbpPJ

**Comment by koekeishiya** [comment] 2018-02-09 19:52
So the effects you are seeing now is related to something else I was trying to fix, which appears to have had other side-effects (#45 #313). I've removed this again for now.

**Comment by enazn** [comment] 2018-02-09 20:03
@koekeishiya interesting. Just for clarification in case it helps, my setup is just a mac mini with a single monitor and no connecting or disconnecting of additional displays.

**Comment by koekeishiya** [comment] 2018-02-09 20:04
Apple is doing some crazy things behind the scenes when the machine goes to sleep / wakes from sleep, so yeah..

**Comment by enazn** [comment] 2018-02-09 20:13
I'll probably start using the caffeine app then and call it a day. BTW, absolutely love your work.

**Comment by koekeishiya** [comment] 2018-02-09 20:14
The latest master now should be working I believe.

**Comment by koekeishiya** [comment] 2018-02-09 21:23
Closing this. Let me know if you still have problems regarding this.

**Closed by koekeishiya** 2018-02-09 21:23 UTC
