### ISSUE TITLE
configure border position

### ISSUE THREAD

**Issue by TheAceShinigami** [koekeishiya/chunkwm#402] opened 2018-05-07 02:19 UTC
When you increase border width, it grows towards the center of the window. It would be nice if you can make borders grow in the other direction, for people who like really thicc borders.

**Comment by dominiklohmann** [comment] 2018-05-07 08:40
if you want to change this locally for yourself, you can easily do that here:

https://github.com/koekeishiya/chunkwm/blob/f4f5dd4672a8f205e40d0bcf9d0ac47c90f66253/src/common/border/border.mm#L91-L113

Simply subtracting `BorderWidth` from `X` and `Y` and adding `2*BorderWidth` to `W` and `H` should do the trick if I'm not mistaken. Although you might run into issues where the borders don't quite match the rounded corners of some windows.

**Comment by koekeishiya** [comment] 2018-05-07 20:27
Dupe of #341 

I'm not super-interested in this, so not something I will be spending time on yet. There are other issues that I consider more important that I need to be spending whatever time I have to try work out some solutions to.

I'm not opposed to this idea if someone would like to try and implement support for this and submit a PR. It would be nice to have #336 fixed at the same time, and also have the same border-settings available there as well.

**Comment by koekeishiya** [comment] 2018-05-07 20:29
Post from #341 by Jessemillar:

> Is there a way to set the position of the border (e.g. outside, centered, inside)? If I have a thick border size, I'd like to set the border to draw outside the edge of the window instead of centered on the edge so it doesn't cover up the edge of the window's content.

**Comment by koekeishiya** [comment] 2018-09-25 08:33
merged in #508

**Closed by koekeishiya** 2018-09-25 08:33 UTC
Labels: help wanted, suggestion
