### ISSUE TITLE
Extra Invisible Window

### ISSUE THREAD

**Issue by lesseradmin** [koekeishiya/chunkwm#48] opened 2017-05-05 23:38 UTC
An image of the issue is provided as follows.
![image](https://cloud.githubusercontent.com/assets/7121943/25767787/173384cc-31c2-11e7-8bb9-e465224bfb81.png)

The reproduction video is linked [here](https://youtu.be/lWJXu_4Uh9U)

Debug log:
![image](https://cloud.githubusercontent.com/assets/7121943/25767874/ebe5adb2-31c2-11e7-92bb-9492911a0000.png)

Here is another screenshot that shows the extra window:
This is Desktop 1:
![image](https://cloud.githubusercontent.com/assets/7121943/25767993/518fc958-31c4-11e7-9d1f-e93ad826dbaa.png)
This is Desktop 2:
![image](https://cloud.githubusercontent.com/assets/7121943/25767992/45f2028c-31c4-11e7-8e88-72767abfedb8.png)
This is Desktop 3:
![image](https://cloud.githubusercontent.com/assets/7121943/25767996/68195d88-31c4-11e7-9b22-725644ef3333.png)

Seeing from these three images, it seems that the window is universal and it appears on all desktops.

**Comment by koekeishiya** [comment] 2017-05-06 08:10
Are you running debug builds? The log is kinda lacking

**Comment by koekeishiya** [comment] 2017-05-06 18:48
My guess is that chrome reports some sort of additional window, god knows why. This was also a problem back in **kwm** (thought I already applied these fixes to the **chunkwm** core).

**Comment by lesseradmin** [comment] 2017-05-06 20:36
I'll switch to the debug build, I didn't realize I wasn't running it.
Another small random issue I noticed is that in chrome at the top right when I click on the user switch and try to change users the menu disappears. This behavior only happens when running chunkwm. Without chunkwm the menu stays visible. Is this because the overlay menu is detected as another window and is hidden when the mouse goes over the chrome window?

A hack for now is clicking the menu then using arrow keys to select the user you'd like to switch to.

**Comment by koekeishiya** [comment] 2017-05-07 11:58
> Another small random issue I noticed is that in chrome at the top right when I click on the user switch and try to change users the menu disappears. This behavior only happens when running chunkwm. Without chunkwm the menu stays visible. Is this because the overlay menu is detected as another window and is hidden when the mouse goes over the chrome window?

This is caused by the focus-follows-mouse plugin, and isn't related to the tiling plugin, but yeah that is pretty much what is happening there. I'm unable to reproduce without the focus-follows-mouse plugin running.

Feel free to open a new issue to track that if you want. The original invisible window issue has been fixed on master.

**Closed by koekeishiya** 2017-05-07 11:58 UTC
