### ISSUE TITLE
creating a new space is not working on High Sierra

### ISSUE THREAD

**Issue by osamine** [koekeishiya/chunkwm#467] opened 2018-07-21 09:00 UTC
When trying the below hotkey, it sends the window to the last space rather than create a new space. I'm current running macOS High Sierra 10.13.6

```
hotkey :: #229 {
	mod: 'shift'
	mod: 'cmd'
	key: 'n' (0x2d)
	cmd: 'chunkc tiling::desktop --create;\
                  ids=$(chunkc tiling::query --desktops-for-monitor $(chunkc tiling::query --monitor-for-desktop $(chunkc tiling::query --desktop id)));\
                  chunkc tiling::window --send-to-desktop $(echo ${ids##* });\
                  chunkc tiling::desktop --focus $(echo ${ids##* })'
}
```

**Comment by dominiklohmann** [comment] 2018-07-21 09:13
Does it work if you run the command manually in your terminal?

**Comment by koekeishiya** [comment] 2018-07-21 09:31
Did you install the scripting sddition and verify that it is running?

**Comment by osamine** [comment] 2018-07-21 09:33
@dominiklohmann no it doesnt work
@koekeishiya yes I did. All other commands for that require chwm-sa work.

**Comment by dominiklohmann** [comment] 2018-07-21 09:36
What's your `$SHELL --version`?

**Comment by osamine** [comment] 2018-07-21 09:37
zsh 5.3 (x86_64-apple-darwin17.0)

**Comment by dominiklohmann** [comment] 2018-07-21 09:45
- Do you use any other scripting additions related to Dock.app (e.g. through SIMBL)?
- Do you have the latest High Sierra version installed?
- Are you sure that chwm-sa is installed and loaded? 

```sh
# step 1: update chunkwm 

# step 2: disable SIP

# step 3: reinstall chwm-sa
sudo chunkwm --uninstall-sa
sudo chunkwm --install-sa

# step 4: (optional) re-enable SIP

# step 5: load chwm-sa
pkill Dock
```

**Comment by osamine** [comment] 2018-07-21 09:48
* I use SIMBL but not for the dock
* yes
* and yes

I retried reinstalling chwm-sa like you outline but im still getting the same behavior

**Comment by dominiklohmann** [comment] 2018-07-21 09:58
Since you said the other chwm-sa based commands are working, there really isn't much left that can be source of the issue. I'm assuming you tested disabling SIMBL?

Only other thing I can think of right now is your zsh config. `zsh -d -f` opens a new instance of zsh without reading config files.

```sh
zsh -d -f -c "chunkc tiling::desktop --create"
```

Also, does deletion of spaces work?
```sh
chunkc tiling::desktop --annihilate
```

**Comment by osamine** [comment] 2018-07-21 10:07
I just tried the above and neither work. 

I also uninstalled mySIMBL just now but to no avail, neither commands work.

**Comment by koekeishiya** [comment] 2018-07-21 10:41
See edit in my previous post, but out of curiosity: does `chunkc tiling::desktop --focus 1` work?

**Comment by osamine** [comment] 2018-07-22 16:58
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/41103209/43048018-bfb12a2a-8dae-11e8-8ebb-90449e399973.png">
This is the output I get. I'm not sure if maybe Little Snitch might be causing the issue?

**Comment by koekeishiya** [comment] 2018-07-22 17:10
You should be getting 
```
                NSLog(@"[chunkwm-sa] failed to get pointer to addSpace function..");
```
or
```
                NSLog(@"[chunkwm-sa] (0x%llx) addSpace found at address 0x%llX (0x%llx)", baseaddr, add_space_addr, add_space_addr - baseaddr);
```

after the *"dock.spaces found at"* if you are on High Sierra, assuming *Apple's* code is not busted..

OS Version is checked as follows:
```
        NSOperatingSystemVersion os_version = [[NSProcessInfo processInfo] operatingSystemVersion];
        if (os_version.minorVersion == 13) {
            ...
        } else if (os_version.minorVersion == 14) {
            ...
        }
```

The *== 14* block (*Mojave*) executes correctly on my system.

*operatingSystemVersion.minorVersion* is documented here:
https://developer.apple.com/documentation/foundation/nsoperatingsystemversion/minorversion?language=objc

At this point i have no idea what is going on.

**Comment by osamine** [comment] 2018-07-22 17:30
I just confirmed that im running 10.13.6. I think im just going to go ahead and make the jump to the pubic beta. Hopefully its not too buggy.

**Comment by koekeishiya** [comment] 2018-07-24 06:55
Can someone with a high sierra machine (preferably 10.13.6) try and reproduce this?

**Comment by osamine** [comment] 2018-07-25 07:20
Just a heads up that I ended up reverting back from Mojave due to accesibility issues with other software.

After doing a clean install, the window creation feature is working. Thank you guys for all your help.

**Comment by koekeishiya** [comment] 2018-07-25 14:55
I assume you meant "space creation" is working in your last post, if so that is good to hear :)
Closing this.

**Closed by koekeishiya** 2018-07-25 14:55 UTC
