### ISSUE TITLE
Windows do not resize back

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/chunkwm#133] opened 2017-07-11 17:39 UTC
I do not know if this can be considered an issue or not. I notice that at times most of the windows do not resize back at certain times. 
The two times that this has happened to me is after I have restarted the computer and the apps like Safari, Finder, Mail and Firefox loaded at login. 

To fix it, I quit the apps and restart them again. 

![screen shot 2017-07-11 at 10 26 04 am](https://user-images.githubusercontent.com/14360736/28081629-bec1cea6-6624-11e7-8b6a-ac98368f9d15.png)
![screen shot 2017-07-11 at 10 26 36 am](https://user-images.githubusercontent.com/14360736/28081630-bf085b82-6624-11e7-97ca-c9cdc4868ec7.png)

**Comment by knightjp** [comment] 2017-07-12 14:56
Now I've noticed that the same thing happens when the computer wakes from sleep. Has anyone got any ideas?

**Comment by koekeishiya** [comment] 2017-07-12 15:02
> Now I've noticed that the same thing happens when the computer wakes from sleep. Has anyone got any ideas?

Have never experienced this. I use sleep-mode all the time.

Try the following:
Stop chunkwm. (brew services stop chunkwm) if installed with brew.
Remove chunkwm from accessibility settings, and add it back again.

Start chunkwm.

--

You most likely have to do the above after every upgrade, because the binary is different.

**Comment by dominiklohmann** [comment] 2017-07-12 15:05
The sleep issue, does it happen when connected to an external monitor?

**Comment by knightjp** [comment] 2017-07-13 08:38
@dominiklohmann both my monitors are external.. . this is a Mac mini.. 

@koekeishiya If you have never faced the issue, I am not sure. Maybe it is related to changes I made with my chunkwmrc file. 
``` 
#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: The following are config variables for the chunkwm-tiling plugin
#

chunkc set global_desktop_mode           bsp

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     1
chunkc set global_desktop_offset_bottom  1
chunkc set global_desktop_offset_left    1
chunkc set global_desktop_offset_right   1
chunkc set global_desktop_offset_gap     1

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.6

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       4

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0

#
# NOTE: The following are config variables for the chunkwm-border plugin
#

chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width          4
chunkc set focused_border_radius         4
chunkc set focused_border_skip_floating  0

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
#chunkc core::load border.so

chunkc tiling::rule --owner \"System Preferences\" --state tile
chunkc tiling::rule --owner Finder --name Copy --state float

#
# NOTE: if chunkc plugin_dir is not set, the absolutepath is necessary.
#

# chunkc core::load ~/.chunkwm_plugins/tiling.so
# chunkc core::load ~/.chunkwm_plugins/ffm.so
# chunkc core::load ~/.chunkwm_plugins/border.so ```

**Comment by koekeishiya** [comment] 2017-07-13 08:49
@knightjp it is most likely related to multi-monitor setups. I'm only at a single-monitor setup lately.

**Comment by knightjp** [comment] 2017-07-13 08:56
@koekeishiya so chunkwm is not ready for multiple monitor setup? 
Maybe I should go back to kwm

**Comment by koekeishiya** [comment] 2017-07-13 09:33
> I am not entirely sure what does chunkwm have that kwm doesn't at this point. Maybe it is stuff that is noticed only by developers.

200% more stability (kwm crashes a lot), better performance and, lower cpu / memory footprint, for me at least.

Quite a lot of new features regarding tiling; better desktop-serialization, amongst other.
Compare [chunkwm-tiling](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md) with [kwm](https://koekeishiya.github.io/kwm/kwmc.html)

> @koekeishiya so chunkwm is not ready for multiple monitor setup?
Maybe I should go back to kwm

Multi-monitor support is better in *chunkwm* with regards to actual use. However, *chunkwm* currently does not detect when monitors are connected and disconnected. So you need to restart *chunkwm* after any action that causes macOS to change or otherwise touch the internal display settings. (displays go to sleep etc). macOS does a lot of crazy things here, some that are not reliable, so it is a hard problem to solve.

*kwm* actually does have some support regarding detection of disconnected / connected displays, but it is so far from *good* that I do not want to do the same approach for *chunkwm*. Need to investigate the internals a lot more and find a proper solution. *kwm* also crashes a lot during these steps, causing *launchd* to restart it, giving the effect that it *seems* to have worked.

**Comment by knightjp** [comment] 2017-07-13 10:51
@koekeishiya From most of the reviews of kwm that I have read, in comparison to Amethyst, KWM was given a better score in terms of being reliable. The only drawback was the fact that someone who wanted to use it had to edit text based config files. While most developers are content with it, us regular users are sometimes weary about that sort of thing. Fortunately, I'm not a complete novice. I have a background in HTML and basic Linux admin. 

If the developer of kwm says that chunkwm is better, I have no reason to argue. I have to say that it is a real learning experience for me. 
BTW, I'm running this on a fresh, clean install of Sierra. kwm is not even installed on this machine. 
Just chunkwm and khd.

**Comment by knightjp** [comment] 2017-07-15 05:14
The issue happened again... 
![screen shot 2017-07-15 at 9 10 11 am](https://user-images.githubusercontent.com/14360736/28236710-f761425c-693d-11e7-917e-9ee55d3300ec.png)

**Comment by knightjp** [comment] 2017-07-16 16:04
Today I just came home from work and logged in. This is what I saw... 
![screen shot 2017-07-16 at 7 53 36 pm](https://user-images.githubusercontent.com/14360736/28249170-d278445c-6a61-11e7-81df-f9ffeeecdc78.png)

**Comment by Waynekosimoto** [comment] 2017-07-17 19:07
I've been facing this quite often recently along with other issues with the mouse not focusing properly. I'm running one monitor.

**Comment by koekeishiya** [comment] 2017-07-17 19:21
@Waynekosimoto 

Can you provide the related debug log ? (`/tmp/chunkwm.err` and `/tmp/chunkwm.out`)
If you can provide steps to reproduce the problem, that decreases the difficulty of me identifying the potential problem A LOT. I have never encountered this issue myself while using *chunkwm*, and there are a huge list of potential edge-cases or whatever in macOS that depends on specific workflows.

> other issues with the mouse not focusing properly. 

I assume you are running *übersicht*, to draw that statusbar, see #148

**Comment by Waynekosimoto** [comment] 2017-07-24 19:14
chunkwm.err

`chunkwm: invalid command 'plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins'
objc[501]: Class OverlayView is implemented in both /usr/local/opt/chunkwm/share/chunkwm_plugins/tiling.so (0x10e168050) and /usr/local/opt/chunkwm/share/chunkwm_plugins/border.so (0x10e1848b0). One of the two will be used. Which one is undefined.
chunkwm: invalid command 'plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins'
objc[1240]: Class OverlayView is implemented in both /usr/local/opt/chunkwm/share/chunkwm_plugins/tiling.so (0x1124d0050) and /usr/local/opt/chunkwm/share/chunkwm_plugins/border.so (0x10fff78b0). One of the two will be used. Which one is undefined.
chunkwm: invalid command 'plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins'
objc[2465]: Class OverlayView is implemented in both /usr/local/opt/chunkwm/share/chunkwm_plugins/tiling.so (0x10bd50050) and /usr/local/opt/chunkwm/share/chunkwm_plugins/border.so (0x10bd6c8b0). One of the two will be used. Which one is undefined.
chunkwm: invalid command 'plugin_dir /usr/local/opt/chunkwm/share/chunkwm_plugins'
objc[2878]: Class OverlayView is implemented in both /usr/local/opt/chunkwm/share/chunkwm_plugins/tiling.so (0x10b4d9050) and /usr/local/opt/chunkwm/share/chunkwm_plugins/border.so (0x10b4f58b0). One of the two will be used. Which one is undefined.
`

As for the insanely long chunkwm.out

I noticed a lot of OBSERVER ERROR (...appname): The function cannot complete because messaging has failed in some way.

**Comment by knightjp** [comment] 2017-08-02 13:18
![28833787-796b6dfc-76f1-11e7-883b-46f63ee473d8](https://user-images.githubusercontent.com/14360736/28875380-725419c8-77a6-11e7-83b2-c7724be0fe02.png)
I notice that this happens when for me now every single time the computer wakes from sleep.

**Comment by simonsmith** [comment] 2017-11-08 22:07
> However, chunkwm currently does not detect when monitors are connected and disconnected. So you need to restart chunkwm after any action that causes macOS to change or otherwise touch the internal display settings. (displays go to sleep etc)

@koekeishiya Would it be possible to get chunkwm to redetect the current display size via a command? I change monitor a lot and being able to hit a shortcut to update the windows to the new display size would be amazing. Currently have to restart on the command line each time which means I lose my window configuration

**Comment by dominiklohmann** [comment] 2017-11-08 22:14
@simonsmith 

> restart [...] means I lose my window configuration

The discussion in #45 is relevant here, especially this bit:

> In the current state, we already have the entire window-tree (id + node mappings) intact, the part that makes this a hard problem, is when macOS starts moving windows around, when a secondary monitor is disconnected. This causes our window-tree to mutate (which is as expected, because there are now more windows on some other desktop). When a monitor is connected, some or all of these windows will be moved back, and we need to know which window-trees that needs to be undone.

**Comment by dplisek** [comment] 2017-11-27 21:37
I'm not sure I'm in the right thread, but I second @simonsmith's remark two posts up.

My issue is resolution change, connecting/disconnecting monitors, the total area for tiling is incorrect. Tiling works right, but for example only on 2/3 of the screen, the rest is empty. What I do now is I have a binding for the restart of chunkwm and skhd, which I have to execute using `open`, otherwise it doesn't finish when skhd is stopped (even with & and/or nohup):

`ctrl + cmd - r : open /usr/local/bin/restart_window_manager -a iTerm`

Where `/usr/local/bin/restart_window_manager` contains a script that restarts both brew services simultaneously.

This takes quite a while to complete, though, so I would really appreciate it if chunkwm could detect resolution change / total screen size change and update its outer regions automatically.

**Comment by dominiklohmann** [comment] 2017-11-27 21:48
@simonsmith this works for restarting both `chunkwm` and `skhd` without `open`
```
ctrl + cmd - r : launchctl stop homebrew.mxcl.chunkwm \
              && launchctl stop homebrew.mxcl.skhd
```

The `homebrew.mxcl.*` part depends on your launch agent, see `ls ~/Library/LaunchAgents` for how Homebrew installed it. As far as I know this is the quickest way to restart both services. The order is important, since you need to kill `skhd` last.

**Comment by koekeishiya** [comment] 2017-11-28 15:51
@dplisek 

> My issue is resolution change, connecting/disconnecting monitors, the total area for tiling is incorrect.

These are planned, but no ETA so far. For resolution change specifically, hitting `chunkc tiling::desktop --toggle offset` twice should do the trick (for that particular desktop).

> What I do now is I have a binding for the restart of chunkwm and skhd

Not particularly sure why you'd need to restart skhd here, that makes no sense at there is no relation between it and chunkwm.

**Comment by dplisek** [comment] 2017-11-28 16:34
@koekeishiya

Thanks for the tip. @dominiklohmann's restart method is preferable though because it updates all desktops and is really fast. As for why I restart skhd - just personal preference, takes no time and allows me to have a single hotkey in case I need to restart either.

**Comment by koekeishiya** [comment] 2017-11-29 20:56
@dplisek 

Added support for monitor resolution change on master. Restarting chunkwm should no longer be necessary in this scenario. Connection / disconnection is harder to do, and I probably won't delve into that yet.

**Comment by simonsmith** [comment] 2017-11-29 21:33
@koekeishiya Are you planning to tag a new version? I install via the homebrew tap. If not I'll install from master

**Comment by crisidev** [comment] 2017-11-29 22:55
You can install the latest version (master head) from brew using `brew install chunkwm --HEAD`

**Comment by koekeishiya** [comment] 2017-11-30 07:38
@simonsmith 

probably doing a new tag sometime during the weekend.

**Comment by ralphholz-usyd** [comment] 2018-01-24 02:46
I have followed this bug for a while and took conscious steps to rule out a multi-monitor problem. While I do attach an external monitor from time to time, I tried this from a clean boot, nothing attached.

I opened macOS Calendar and iterm. They displayed side-by-side, as expected. When I closed Calendar, iTerm did not resize to fill the space.

To me, this is relatively strong indication that some underlying signalling is going wrong.

**Comment by koekeishiya** [comment] 2018-01-24 06:48
I'm still unable to reproduce. This is the notifications I received when doing the above:
```
10295:Calendar deactivated
10295:Calendar terminated
kitty:tmux attach-session -t 0:6581 window moved
kitty:tmux attach-session -t 0:6581 window resized
```

Opened kitty (terminal I use), then opened Calendar.
Tiled as expected.
Closed Calendar (various ways, close window, quit application)
Window untiled and covered entire screen again.

Seems to be some issue with the macos acccessibility API for some users, for whatever reasons I will conclude is macOS being macOS..

If you have upgraded chunkwm since the first install, you must either re-codesign the binary or uncheck and recheck the accessiblity permissions for things to work properly.

Note that the brew services must be stopped while doing this. The cleanest way is to just codesign the binary once, before granting the permissions. There is an explanation of how to do  this in the homebrew-repo of chunkwm.

**Comment by ralphholz-usyd** [comment] 2018-01-24 11:59
ACK. I am writing to chunkwm.err.log and chunkwm.out.log. I am happy to share the files privately if you want.

Alternatively - is there anything I can grep for in there?

**Comment by koekeishiya** [comment] 2018-01-24 15:17
> Alternatively - is there anything I can grep for in there?

If you have full debug-information enabled you should be able to identify when `Calendar` was launched, and follow the trace from there.

```
c_log(C_LOG_LEVEL_DEBUG, "%d:%s launched\n", Info->PID, Info->ProcessName);
```

Try grep for `Calendar launched`

**Comment by ralphholz-usyd** [comment] 2018-02-11 09:06
I happened to have debug-level logging enabled today when it happened.

Steps:
- Download of PDF via Google Chrome
- Print via System Dialogue
- Show in Preview
- Export in Preview
- Close preview

Caveat: my notebook display was on when this happened, i.e. it was multi-monitor. However, I see no link to it in the debug log.

2018-02-11 20:00:01 DEBUG: carbon: process details
Name: Preview
PID: 2435
PSN: 376924 0
Policy: 0
Background: 0
2018-02-11 20:00:01 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-11 20:00:01 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationDeactivated'
2018-02-11 20:00:01 DEBUG: 734:Google Chrome deactivated
2018-02-11 20:00:02 DEBUG: 2435:Preview successfully registered window notifications
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationLaunched'
2018-02-11 20:00:02 DEBUG: 2435:Preview launched
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowFocused'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window focused
2018-02-11 20:00:02 DEBUG: chunkwm:Tiling:focused_window_float
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowCreated'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window is not destructible, ignore!
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowResized'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window resized
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Google Chrome:1234:248 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowResized'
2018-02-11 20:00:02 DEBUG: Google Chrome:1234:248 window resized
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-11 20:00:02 DEBUG: 2435:Preview activated
2018-02-11 20:00:02 DEBUG: chunkwm:Tiling:focused_window_float
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginBroadcast'
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Google Chrome:1234:248 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-11 20:00:02 DEBUG: Google Chrome:1234:248 window moved
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginBroadcast'
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window title changed
2018-02-11 20:00:02 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window title changed
2018-02-11 20:00:06 DEBUG: carbon: process details

**Comment by koekeishiya** [comment] 2018-02-11 11:58
So I noticed in your log: `2018-02-11 20:00:02 DEBUG: Preview:1234.pdf:1476 window is not destructible, ignore!` This happens because https://github.com/koekeishiya/chunkwm/blob/3b86991f3c6ad23f2dec1e380224e4d23be73aca/src/core/state.cpp#L49 returns false.

This is the function that is responsible for registering for the *window destroyed (closed)* notification which we rely on to know when to untile a window.

Why this fails, I don't know. There is a lot of crazy stuff happening in macOS.. especially in their *accessibility API*, which is sadly the foundation of everything that we are able to do.

**Comment by koekeishiya** [comment] 2018-02-11 12:03
So this problem seems to be the same as the one that was encountered here: https://github.com/koekeishiya/kwm/issues/401#issuecomment-239139597 Specifially, the *edited* part of my comment there:

> Regarding preview, after some testing I figured that if I open a pdf, and close it again, it will leave a ghost window. Any subsequent preview windows I open after that (without terminating the preview app) does get removed properly and the tree is rebalanced as expected.

I don't understand why though, as *chunkwm* already incorporates whatever change was made to resolve that issue in the past.

**Comment by ralphholz-usyd** [comment] 2018-02-11 12:20
Could this be related to the way a window is closed? I have a (un-Mac-like) habit of Cmd-Q-ing.

**Comment by koekeishiya** [comment] 2018-02-11 12:33
Nah that shouldn't matter at all.

**Comment by ralphholz-usyd** [comment] 2018-02-12 00:54
I just happened to be sitting on the train with no second monitor, so here is the same situation again (literally the same workflow). The effect is different here, but still wrong: instead of tiling, preview took the full screen (and also gave it back).

No idea if that is helpful. The one thing I can see is the  Finder:<unknown>.

Let me know if you have workflows you want me to test.

2018-02-12 11:49:36 DEBUG: 962:Preview launched
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowFocused'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window focused
2018-02-12 11:49:36 DEBUG: chunkwm:Tiling:focused_window_float
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowCreated'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window is not destructible, ignore!
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window moved
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowResized'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window resized
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-12 11:49:36 DEBUG: 962:Preview activated
2018-02-12 11:49:36 DEBUG: chunkwm:Tiling:focused_window_float
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginBroadcast'
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window moved
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowMoved'
2018-02-12 11:49:36 DEBUG: Preview:1234.pdf:774 window moved
2018-02-12 11:49:36 DEBUG: chunkwm: processing event of type 'ChunkWM_PluginBroadcast'
2018-02-12 11:49:37 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-12 11:49:37 DEBUG: Preview:1234.pdf:774 window title changed
2018-02-12 11:49:37 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-12 11:49:37 DEBUG: Preview:1234.pdf:774 window title changed
2018-02-12 11:49:38 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-12 11:49:38 DEBUG: Preview:1234.pdf:774 window title changed
2018-02-12 11:49:38 DEBUG: chunkwm: processing event of type 'ChunkWM_WindowTitleChanged'
2018-02-12 11:49:38 DEBUG: Preview:1234.pdf:774 window title changed
2018-02-12 11:49:45 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-12 11:49:45 DEBUG: 602:Google Chrome activated
2018-02-12 11:49:45 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationDeactivated'
2018-02-12 11:49:45 DEBUG: 962:Preview deactivated
2018-02-12 11:49:46 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-12 11:49:46 DEBUG: 962:Preview activated
2018-02-12 11:49:46 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationDeactivated'
2018-02-12 11:49:46 DEBUG: 602:Google Chrome deactivated
2018-02-12 11:49:47 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationActivated'
2018-02-12 11:49:47 DEBUG: 872:Microsoft Outlook activated
2018-02-12 11:49:47 DEBUG: chunkwm:Tiling:focused_window_float
2018-02-12 11:49:47 DEBUG: chunkwm: processing event of type 'ChunkWM_ApplicationDeactivated'
2018-02-12 11:49:47 DEBUG: 962:Preview deactivated
2018-02-12 11:49:47 DEBUG: chunkwm: processing event of type 'ChunkWM_SpaceChanged'
2018-02-12 11:49:47 DEBUG: Finder:<unknown> is not destructible, ignore!

**Comment by koekeishiya** [comment] 2018-02-12 16:45
I think this issue has been fairly derailed from its original purpose. I still can't reproduce the original issue as mentioned in the very first post.

The issue mentioned by @ralphholz-usyd regarding *preview* has been identified and fixed on master.
The problem could potentially have affected other applications as well, and that would also sort out that error.

If anyone else is able to reproduce other weird behaviour, please do create a new issue with as much details for how to reproduce as possible.

**Closed by koekeishiya** 2018-02-12 16:45 UTC
Labels: bug, need steps to reproduce

**Comment by ralphholz-usyd** [comment] 2018-02-13 12:59
Had a look at the commit - interesting one. Thanks!
