### ISSUE TITLE
OS X monitor wake from sleep handling

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/chunkwm#14] opened 2017-02-19 20:11 UTC
`kwm` sometimes (Probably 1 time out of 10) freaks out during the wake from sleep "dance" (removing and adding the monitor) that OS X does to wake a 4k display. 

"Freak out" means that when the display is finally awake and the computer is unlocked `kwm` doesn't see the main monitor _at all_ until I `killall kwm` and send all the windows back to their original display. At this point the tiling is all messed, up: It is only using a portion of the main display. So I must `killall kwm` again, then everything is back to normal. 

I am wondering if there is a different approach that `chunkwm` could take that would make the wake from sleep experience better? 

Could tiling be disabled entirely while OS X is locked? 
Could tiling be disabled while monitors are being added and removed? 

I'm really unsure the best approach here, if there even is one. 

All I know is having to re-arrange all my windows after a "freak out" makes me a sad panda. 

Thanks!

**Comment by koekeishiya** [comment] 2017-02-21 15:29
Displays are probably not going to be tracked in **chunkwm** at all, at least as little as we can get away with.

I find that caching over-aggressively causes problems, and this is a prime example of exactly that.
I am experimenting with not caching any display state for now, only our `virtual spaces`.

Whenever we want to access a `virtual space`, we request the required information from the OS.

This also lets us not have to "care" about displays at all, we just talk about spaces. We want to tile a window on a space. It shouldn't matter to us if that space is on a separate display or not. 
This also lets the end-user be able to always refer to a space in his system by using the index that mission control is showing during expose.

We track spaces using their UUID (same as in **kwm**), which is supposed to be unique and permanent (until the space is removed in mission control). 

I can't say if this would cause any change in the above behaviour that you are having with **kwm**, but a different approach can't hurt / make it worse (hopefully..).

**Comment by chrishoage** [comment] 2017-02-21 18:32
> Displays are probably not going to be tracked in chunkwm at all, at least as little as we can get away with.

Will display commands, for example sending a window to a specific display still work?

**Comment by koekeishiya** [comment] 2017-02-21 18:33
> Will display commands, for example sending a window to a specific display still work?

The plan is for this to remain a feature yes, as well as integrating https://github.com/koekeishiya/kwm/issues/277

**Comment by koekeishiya** [comment] 2017-03-09 21:09
Sending a window to a monitor can be done using `chunkc window -m <prev | next | arrangement_id` (same behaviour as in **kwm**).

Sending a window to an arbitrary space can be done using `chunkc window -d <prev | next | desktop_id>`
This command uses the desktop index shown in mission-control expose, and works across monitor boundaries, as described in https://github.com/koekeishiya/kwm/issues/277.

The implementation still requires quite some fixes to be worth even looking at, see mentioned todos: https://github.com/koekeishiya/chunkwm/commit/b0ff62294248b68ddf71608a910dc9f88c860d6e

**Comment by chrishoage** [comment] 2017-03-09 21:10
Awesome, multiple monitor support is one of the last things missing from chunkwm that has been keeping me from trying it out. 

Time to experiment this weekend!

**Comment by koekeishiya** [comment] 2017-03-09 21:43
> Awesome, multiple monitor support is one of the last things missing from chunkwm that has been keeping me from trying it out.

> Time to experiment this weekend!

Hate to break the ice, but multiple monitor support is still far and long away from usable.

**Comment by koekeishiya** [comment] 2017-05-07 13:14
I suppose this is a dupe of #45, closing this one.

**Closed by koekeishiya** 2017-05-07 13:14 UTC
