### ISSUE TITLE
Windows that are fullscreen when chunkwm is started cannot be tiled

### ISSUE THREAD

**Issue by nanzhong** [koekeishiya/chunkwm#407] opened 2018-05-09 11:42 UTC
Windows that are already fullscreen (macOS fullscreen) when chunkwm starts don't seem to be recognized by the tiling plugin when fullscreen is disabled.

Manually toggling float/tile does not work nor does changing the desktop's tiling mode.

**Comment by koekeishiya** [comment] 2018-05-17 17:38
The reason for this is that macOS reports to us that the window is NOT movable in these cases.

When an application window enters fullscreen, the internal APIs actually creates a new window (at the WindowServer), and when the window exits fullscreen, this NEW window is destroyed.

So when for example *Notes.app* is already running, and in fullscreen, and we start chunkwm,
the first time we see *Notes.app*, we find a fullscreen window, and this is correctly handled.

When we then exit fullscreen for *Notes.app*, the internal API first creates the new *Notes.app* mainwindow, that is the non-fullscreen version, and THEN it sends a window destroyed message for the "fake" fullscreen window.

The problem is that while the new window is created, the *is this window movable* API call that we do returns false for whatever reason..

A dummy fix is to just add a user-command that could reevaulate the current application and its windows, but I'm not a fan of this, because I feel like this should be completely transparent to the user. I have not yet come up with an idea that would let chunkwm automatically handle this issue.

**Comment by koekeishiya** [comment] 2018-08-01 16:24
I am no longer able to reproduce this in the latest version of chunkwm. Note that I am also running *macOS Mojave (10.14 Beta)* and so that could be because this has been fixed due to changes made by Apple.

**Comment by koekeishiya** [comment] 2018-08-03 10:42
Closing this. See my comment above.

**Closed by koekeishiya** 2018-08-03 10:42 UTC
Labels: bug
