### ISSUE TITLE
Padding issues with two monitors (vertical)

### ISSUE THREAD

**Issue by ma-con** [koekeishiya/chunkwm#293] opened 2017-12-06 09:40 UTC
Since updating to the newest version via homebrew, I seem to have a problem with the top and bottom padding when I'm using two monitors. I use the screen of my MacBook placed left of my main screen (a 4k monitor). 

As long as I use only the internal screen, everything is as configured in .chunkwmrc and as with the previous versions. As soon as I use two screens, on the main monitor (external), the padding on the bottom is too little and the padding on the top is too large. At the bottom the windows go behind the dock although I have set 
`chunkc set global_desktop_offset_bottom  5`

I have also noticed that windows "jump up and down" when I'm resizing them vertically.

Edit: It seems that chunkwm thinks that the dock is on the internal monitor, although it is on the external one. When the internal monitor is used as a secondary, the bottom offset is way too large, just as if the dock was there.

Screenshots

MacBook display only:
<img width="960" alt="internal" src="https://user-images.githubusercontent.com/3628261/33655194-b1a7c15e-da72-11e7-8c57-b2e0bcc4844d.png">

Two monitors
Main monitor (external):
<img width="960" alt="two monitors" src="https://user-images.githubusercontent.com/3628261/33655195-b1c06f56-da72-11e7-8964-43dcab35dfab.png">
Secondary (internal):
<img width="960" alt="two monitors 2" src="https://user-images.githubusercontent.com/3628261/33655525-8ee125ba-da73-11e7-8217-f767566ee1cf.png">

**Comment by dominiklohmann** [comment] 2017-12-06 12:02
Likely caused by #291.

**Comment by ma-con** [comment] 2017-12-06 12:52
It probably is. The problem happens only when the two monitors are aligned at the bottom in system preferences, when the secondary monitor is "higher" than the primary, the problem does not occur.

Works: 
<img width="762" alt="bildschirmfoto 2017-12-06 um 13 50 49" src="https://user-images.githubusercontent.com/3628261/33662588-91dc3a3e-da8c-11e7-871c-8bf2388396ee.png">

Leads to the problems mentioned:
<img width="762" alt="bildschirmfoto 2017-12-06 um 13 51 19" src="https://user-images.githubusercontent.com/3628261/33662593-9b4dad5a-da8c-11e7-974b-b758359825f5.png">

**Comment by koekeishiya** [comment] 2017-12-06 12:58
@ma-con 

Sorry for the inconvenience. I noticed this issue a little bit after doing the latest release. I have a potential fix in mind, but no ETA for when I will have time to implement it.

**Comment by ma-con** [comment] 2017-12-06 13:01
no worries, aligning the monitors as in the previous post is an easy enough workaround. 
I wouldn't want to use my mac without chunkwm, thanks a lot for all the effort you put in it.

**Comment by koekeishiya** [comment] 2017-12-11 17:13
This issue has now been fixed on master.

**Closed by koekeishiya** 2017-12-11 17:13 UTC
Labels: bug

**Comment by tinder-jonathanwilner** [comment] 2017-12-22 20:05
@koekeishiya - at least for me, this is now happening for me with master. :-( . Thought I might have a config/old binaries problem. Started from scratch and still there. I'm running with either 2 or 3 monitors arranged horizontally. Main monitor is LG 5K to the left of the MacBook Pro. Workaround remains to virtually position the main monitor lower than the others.

**Comment by ma-con** [comment] 2018-01-17 14:12
I've also seen the bug again recently. But in contrast to before, it only seems to happen if one of the non-primary monitors is positioned below the main monitor:

Works:
<img width="668" alt="screen shot 2018-01-16 at 14 15 50" src="https://user-images.githubusercontent.com/3628261/35046889-a56bcea2-fb98-11e7-9723-993040638a45.png">

Doesn't work, Windows are behind the dock:
<img width="668" alt="screen shot 2018-01-16 at 14 15 43" src="https://user-images.githubusercontent.com/3628261/35046906-b210cf4a-fb98-11e7-8ec0-d0e52f121b97.png">

**Comment by koekeishiya** [comment] 2018-01-17 14:29
@ma-con 

In my experience, the right-most monitor would get the dock in this case. Not sure what macOS does to decide this. I suppose this commit could be reverted though, if it doesn't actually improve anything.

Before this commit, we would always assume that the Dock is visible on the primary monitor, when "docked" at the bottom.

**Comment by ma-con** [comment] 2018-01-17 14:34
I just used this setting for a short time yesterday, but there the dock stayed at the primary monitor (in the middle). 
Sometimes the dock appears on the left or the right monitor, but I can't really replicate this. I can bring it back by hiding the dock, and unhiding it while on the primary monitor.

For me, the commit from december 11th improved the situation a lot, before I had the problem, even when displays where aligned at the bottom. Now it seems to only occur, if there is a secondary display that is below the primary...

**Comment by koekeishiya** [comment] 2018-01-17 14:51
@ma-con 

Ah, my bad; should've been clearer.

I meant that it may be better to undo the changes made in: https://github.com/koekeishiya/chunkwm/issues/291
The changes on december 11th was a response to that change.

**Comment by ma-con** [comment] 2018-01-18 09:08
I don't remember any problems before #291. 
At least from my experience, the dock is on the primary monitor when at the bottom, and if it's not it seems to be an error of macOS, but I might be wrong there...

**Comment by koekeishiya** [comment] 2018-01-18 18:34
reverted the changes made in #291 on master.
