### ISSUE TITLE
[plufin|ffm] Introduce a lot of lag when focusing a window on another monitor

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/chunkwm#247] opened 2017-10-04 16:36 UTC
It looks like I finally isolated an issue that I have with (chun)kwm since a lot of time.

I use ffm and when I move my mouse to a window on another desktop, it takes ages (around 1 second or more) to focus the window and it loses some mouse clicks.

It looks like this is directly related to the ffm plugin. Is this a known issue ?

**Comment by chrishoage** [comment] 2017-10-04 17:38
I can no repo 1 second delay using ffm to focus a window on another desktop, at least in monocle mode. 

So if its truly a ffm issue its more subtle than it being a problem for everyone in all cases.

**Comment by koekeishiya** [comment] 2017-10-04 19:13
The responsiveness of focus switch will depend on how fast said application responds to messages sent using the AX API. A busy application takes noticaly longer to respond to AX messages that we issue. Assuming this is the issue, there is nothing we can do about it.

**Comment by mickaelperrin** [comment] 2017-10-05 09:39
Thanks for your answers,

What I don't understand is why with ffm enabled, I loose clicks when I try to interact with a window on another monitor.

For example, here is my workflow:

Integrated Monitor: IntelliJ Idea (IDE)
Left monitor: Real time logs (2 iterm windows)
Top monitor: Browser (Chrome)
Right monitor: Debugging window (Panel of IntelliJ Idea) (USB monitor with DisplayLink driver)

And the issue I encounter:

1. Work on IDE. Start a debugging session.
2. Click refresh on browser.
3. Go to debugging panel, and toggle step-by-step button.

It appears that often:
- The window doesn't respond to the click (action is not performed)
- The border blink multiple times around the window
- Then I can perform the action

This happen in a time frame of around 1-2 seconds.

However, while writing this post, I followed the previous instructions and don't encouter the issue.

I noticed that while using the debugging in IntelliJ the memory consumed by the application grows to the max allowed (4Go in my case). Maybe, this happens when the application uses a lot of  memory and reach it's maximum allowed ?

I also noticed that the menu bar icons are redrawing each time I change of monitor, as described in this [Ask Different](https://apple.stackexchange.com/questions/152038/prevent-redraw-of-menu-bar-icons-yosemite) thread. But this looks like unrelated to chunkwm as it appears even with chunkwm disabled. It looks like it appears only when the USB monitor is plugged.

So, finally, could these issues be related the Display Link driver ?

**Comment by dominiklohmann** [comment] 2017-10-05 15:02
I can confirm this behaviour with 3 monitors, but not when using 2. Nothing is different in the logs, it's just that ffm takes way longer (estimated 0.5 seconds instead of 0.1 seconds) for activating a new monitor.

**Comment by valentjedi** [comment] 2017-10-07 16:20
HI there, I'm having the same issue with two-monitor setup. It's just google chrome on the second monitor. When I switch from fullscreen view, I have to wait for about 1-1.5 sec for chrome will be able to receive my clicks.

**Comment by TheEmpty** [comment] 2017-10-09 21:32
I have the same issue with Chrome and FFM. But using a single (wide) monitor, external, macbook pro closed.

**Comment by koekeishiya** [comment] 2017-10-10 07:07
Is this reproducable with other applications than Chrome?

**Comment by koekeishiya** [comment] 2017-10-10 07:13
I don't see any immediate issues in the code that could cause said issues. I still believe this is related to the internals of the AX API as I mentioned in my previous post.

The following are the relevant parts of the ffm plugin:
[detecting the topmost window](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/ffm/plugin.cpp#L89)
[giving the window focus](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/ffm/plugin.cpp#L56)

**Comment by dominiklohmann** [comment] 2017-10-10 08:30
This really seems to be a perf issue. It exists regardless of Chrome, but for whatever reason the responsiveness takes a dive with Chrome especially.

**Comment by mickaelperrin** [comment] 2017-10-10 08:50
As I mentioned previously, in my use case, I encounter the issue with both my IDE (IntelliJ/phpStorm) and Chrome.

**Comment by TheEmpty** [comment] 2017-10-10 08:51
I don’t have the issue with KWM for what that is worth.

**Comment by dominiklohmann** [comment] 2017-10-10 08:53
IIRC the only difference between the ffm implementations in chunkwm and Kwm is the use `CGSFindWindowByGeometry`. Looks like this requires some benchmarking.

**Comment by koekeishiya** [comment] 2017-10-10 10:39
> Random Idea: what if ffm was not triggered for every mouse moved event, but rate limited instead?
  
That's more or less what the below code is for:
```
if(Connection == WindowConnection) return;
if(WindowId == FocusedWindowId)    return;
```

I did experiment with liming the number of mouse moved events we respond to, at some point, but that made it feel bad from a use-perspective. 

From my testing during the rewrite, the *CGSFindWindow..* function finished near instantaneously, granted I was only using 2 active monitors at the time. My experience after the rewrite has been better responsiveness and lower CPU usage.

I have a very hard time believing that the private API call to identify the topmost window is slower than the previous method (call *CGWindowListCopyWindowInfo*, looping through the list and matching values from the corresponding dictionary).

Anyway, if someone that is able to reproduce the problem could do some performance monitoring, that would be great.

I usually use something like the below to get some rough numbers:
```

#define BEGIN_TIMED_BLOCK() \
    clock_t timed_block_begin = clock()
#define END_TIMED_BLOCK() \
    clock_t timed_block_end = clock(); \
    double timed_block_elapsed = (timed_block_end -timed_block_begin) / (double)CLOCKS_PER_SEC; \
    printf("elapsed time: %f\n", timed_block_elapsed)


BEGIN_TIMED_BLOCK();

// do some code that we want to profile

END_TIMED_BLOCK();
```

**Comment by koekeishiya** [comment] 2017-10-10 10:43
For comparison, this is how *kwm* implements *ffm*:

[Find topmost window](https://github.com/koekeishiya/kwm/blob/master/axlib/axlib.cpp#L217)
[Focus window](https://github.com/koekeishiya/kwm/blob/master/kwm/cursor.cpp#L372)

Note that the topmost window function in *kwm* is not as precise as the one in *chunkwm*.

**Comment by koekeishiya** [comment] 2017-10-10 11:14
Another important thing to notice is that *ffm* in *kwm* had all window and application information cached, whereas *chunkwm* does not. Thus the following code that we require in *chunkwm*, is never ran in the *kwm* implementation. Again, these are calls to the AX API, which is where I believe the problem lies.

```
    AXUIElementRef ApplicationRef;
    CFArrayRef WindowList;
    CFIndex WindowCount;

    ApplicationRef = AXUIElementCreateApplication(WindowPID);
    if(!ApplicationRef) goto out;

    WindowList = (CFArrayRef) AXLibGetWindowProperty(ApplicationRef, kAXWindowsAttribute);
    if(!WindowList) goto app_release;
```

**Comment by crisidev** [comment] 2018-01-25 18:26
Building last commit commit completely disable follow-focus-mouse. Now I need to click on a window to focus it. Am I the only one?

**Comment by crisidev** [comment] 2018-01-25 18:30
Correction, it happens only with window of the same type. If I am moving the mouse between two iTerms or two Chrome windows, the focus does not change. If I am moving the mouse between Chrome and iTerm, the focus follows.

**Comment by koekeishiya** [comment] 2018-01-25 18:35
> If I am moving the mouse between two iTerms or two Chrome windows, the focus does not change.

Weird, that works just fine here. hmm..

**Comment by dominiklohmann** [comment] 2018-01-25 18:38
Same issue on my end, ffm does not work at all between windows of the same application with current master.

**Comment by koekeishiya** [comment] 2018-01-25 18:39
OK there is definitely something funky going on sometimes,  but I can't reproduce it 100%. Only sometimes (can reproduce using Terminal.app) but not with Chrome or Firefox.

**Comment by koekeishiya** [comment] 2018-01-25 19:18
@dominiklohmann  
@crisidev 

Right, could you try the latest commit and let me know if that solved it?

**Comment by dominiklohmann** [comment] 2018-01-25 19:19
Seems to work just fine.

**Comment by crisidev** [comment] 2018-01-26 09:45
Yep, also for me. And performances looks to be improved. Thanks!

**Comment by koekeishiya** [comment] 2018-01-26 11:05
I'm gonna close this for now, as I don't think there are further optimizations that can be applied. Hopefully this has improved the situation somewhat.

**Closed by koekeishiya** 2018-01-26 11:05 UTC

**Comment by TheEmpty** [comment] 2018-01-26 16:15
For feedback: used it for ~24 hours, haven't had an issue with Chrome and missing mouseclicks.

**Comment by garymm** [comment] 2019-02-20 22:59
I'm seeing really sluggish performance in Chrome with FFM enabled. It seems like it started around the time I upgraded to MacOS Mojave.
I'm currently using MacOS 10.14.3.

```
➜  brew info chunkwm
koekeishiya/formulae/chunkwm: stable 0.4.7, HEAD
```
It's much worse when I'm using a large external monitor, but I also notice it even using just the built-in display.

Should I file another bug about this?
