### ISSUE TITLE
Safari untiles upon a weird condition

### ISSUE THREAD

**Issue by rzhikharevich** [koekeishiya/chunkwm#306] opened 2018-01-07 19:17 UTC
Steps to reproduce:
1. Open a Safari window, open a yet another window (of any app).
2. Visit https://doc.rust-lang.org/std/marker/trait.Copy.html

chunkwm puts Safari into the floating mode.

**Comment by koekeishiya** [comment] 2018-01-08 15:06
I'm not able to reproduce this. Do you by chance have a window rule that matches based on the window title ?

**Comment by rzhikharevich** [comment] 2018-01-08 15:37
Only the default ones:

    chunkc tiling::rule --owner Finder --name Copy --state float
    chunkc tiling::rule --owner \"App Store\" --state float

**Comment by rzhikharevich** [comment] 2018-01-08 20:21
I've just commented out these two lines and it stopped untiling Safari. Looks like chunkwm doesn't check the owner property?

**Comment by koekeishiya** [comment] 2018-01-08 20:25
> I've just commented out these two lines and it stopped untiling Safari. Looks like chunkwm doesn't check the owner property?

It should, I have those rules set as well. Definitely seems like something weird is going on though. Will have to take a deeper look at some point.

**Comment by blahsd** [comment] 2018-01-27 19:40
Please try the following:

`chunkc tiling::rule --name Copy --state float`

then try opening the page you linked. If I'm right, this will untile Safari.

What I think is that the title of a page open in Safari is eligible to satisfy the condition of `--name`. Therefore if the word "copy" is in the title of the page you're opening, it will satisfy the condition and will untile. If so, it would appear that the conditions which are prerequisite for a rule to activate, namely in this case the flags `--owner` and `--name` are not checked against cumulatively but alternatively.

**Comment by koekeishiya** [comment] 2018-01-29 19:06
Hmm I'm unable to reproduce this, having the same rules defined as listed in the previous post.
I've gone through the code for matching rules a couple of times as well, and I don't see any immediate errors there either.

All filters must match for the rule to trigger, so they are not matched alternatively as suggested above.
As I'm unable to reproduce this issue, I'll be closing it for now.

If anyone is able to reproduce this in the latest version (or on master), please do create a new issue.

**Closed by koekeishiya** 2018-01-29 19:06 UTC
