### ISSUE TITLE
Windows re-arranged (lose state) on screen unlock

### ISSUE THREAD

**Issue by ricelid** [koekeishiya/chunkwm#340] opened 2018-02-09 18:17 UTC
I have macbook with lid closed connected to external monitor.
3 windows open, tiling binary tree mode on all of them. I shift their positions and sizes.
I lock the screen. Walk away for a few minutes, display goes to sleep.
Wake up display, enter my password, unlock the screen.
The windows immediately get rearranged and resized to what appears to be a default (one window on the right takes up half the screen, two on the left each take 1/4).

Not sure if this has already been reported, but I couldn't find anything.

**Comment by ricelid** [comment] 2018-02-09 18:20
Possibly a dupe of https://github.com/koekeishiya/chunkwm/issues/45? If so, sorry.

**Comment by koekeishiya** [comment] 2018-02-09 20:32
Assuming you are building from master, and not the latest stable release, this was caused by some experimental changes. These have been removed again.

**Comment by koekeishiya** [comment] 2018-02-09 21:24
Closing this. Should be fixed on master.
Let me know if this happens, and we can reopen the issue (or open a new one).

**Comment by ricelid** [comment] 2018-02-13 20:44
I'm using the latest version from homebrew (0.2.36)
My guess is the display goes to sleep and then comes back, triggering something similar to #45, but I'm not sure.

**Comment by ricelid** [comment] 2018-02-13 20:45
Oh, and I can't re-open this issue since I didn't close it.

**Comment by marcjoha** [comment] 2018-03-29 13:31
Same issue here. Laptop closed with external monitor. Waking the computer after it's been sleeping will rearrange the windows.

**Closed** 2018-03-29 13:43 UTC
